# Generated by Django 4.2.3 on 2023-07-03 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_curso_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.PositiveSmallIntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='curso')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sitio.marca')),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
